spring:
  application:
    name: shop
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  batch:
    jdbc:
      initialize-schema: never
  task:
    scheduling:
      cron:
        settlement: 0 0 0 * * *

api:
  v1: /api/v1

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY}

settlement:
  async:
    pool-size: 5
    enabled: false
